src/DynamicExpresso.Core/ParserArguments.cs
test/DynamicExpresso.UnitTest/ParametersTest.cs

Hello David!
A month ago I started using your library for my new project because is hasn't bugs that were in the original implementation of Microsoft (e.g. parsing of real numbers depends on the settings of the culture). 
Recently I found one bug which I want to notify you. The bug is as follows: order of params, that transfer to Lambda.Invoke() method should be the same as order of parameters, transfered to Interpreter.Parse() method, but is the same as the order in which the parameters are occured in the expression.
See example:
```C#
var Parameter1 = new Parameter("a", typeof(int));
var Parameter2 = new Parameter("b", typeof(int));
var expr = new Interpreter().Parse("b-a", Parameter1, Parameter2);
Console.WriteLine(expr.Invoke(1, 2));
Console.ReadLine();
```
Expected: 1 (as a = 1, b = …

Resolve bug about expected order of parameter when do lambda.Invoke call 

---

src/DynamicExpresso.Core/Interpreter.cs
src/DynamicExpresso.Core/Parsing/ParserSettings.cs
src/DynamicExpresso.Core/ReferenceType.cs
src/DynamicExpresso.Core/Reflection/ReflectionExtensions.cs
test/DynamicExpresso.UnitTest/DynamicExpresso.UnitTest.csproj
test/DynamicExpresso.UnitTest/PerformanceTest.cs

Hi,
I've been using DynamicExpresso indirectly via @Alex141 's CalcBinding library, and it is fantastic!
However, when using the library extensively I've found there to be a performance issue inside of Interpreter constructor. 
Here is a profiling snapshot from dotTrace:
I later created a test and found that creating 1000 Interpreter instances on my modern machine took just over 4 seconds.
I've eliminated the problem by adding a few fixes:
1. Switched to using a HashSet instead of a List
2. Only load the extension methods once per primitive type
3. Only attempt to read extension methods from System.Type's that represent static classes (both .IsSealed and .IsAbstract are true)
Added a unit test to prevent regression.

Fixed performance issue where Interpreter's ctor ran too slow

---

src/DynamicExpresso.Core/Parsing/Parser.cs
test/DynamicExpresso.UnitTest/MemberInvocationTest.cs

I.e. expression is "Utils.Max(1, 2, 3)" and there are methods
`int Max(params int[] values)`
`long Max(params long[] values)`
In such case lib method Parser.FindBestMethod has more than 1 applicable methods and invokes method MethodHasPriority.
In this method there's no check if parameters have ParamsArrayType and it throws exception on method.Parameters[i] "Out of range" exception.
I've handled this situation in the method MethodHasPriority.

Fix: >1 overload params[] methods suit given args

---

src/DynamicExpresso.Core/DynamicExpresso.Core.csproj
src/DynamicExpresso.Core/Parsing/Parser.cs
test/DynamicExpresso.UnitTest/DynamicExpresso.UnitTest.csproj
test/DynamicExpresso.UnitTest/DynamicTest.cs

Proposal for dynamic implementation and testing

---

src/DynamicExpresso.Core/Parsing/Parser.cs
test/DynamicExpresso.UnitTest/MemberInvocationTest.cs

At the moment, calling a method with default arguments without defining them explicitly causes a failure:
Consider this example:
```
class Program
{
class test
{
public string abc(int a, int b = 5, int c = 10)
{
return (a + b +c).ToString();
}
}
static void Main(string[] args)
{
Interpreter a = new Interpreter();
a.SetVariable("Test", new test());
Console.WriteLine(a.Eval<string>("Test.abc(2)")); //fails
Console.WriteLine(a.Eval<string>("Test.abc(2,5)")); //fails
Console.WriteLine(a.Eval<string>("Test.abc(2,4,11)")); //ok
//Console.WriteLine(a.Eval<string>("Test.abc(2,4,11,12)")); // correct to be fail
//Console.WriteLine(a.Eval<string>("Test.abc()")); // correct to be fail
Console.ReadKey();
}
}
```
The first and second eval will fail with an exception saying no suitable method was found …

Support calling functions with default parameters

---

src/DynamicExpresso.Core/Parsing/Parser.cs
test/DynamicExpresso.UnitTest/GithubIssues.cs

FIX #88 calculations not working with non nullables and nullables numbers

---

src/DynamicExpresso.Core/Parsing/Parser.cs
src/DynamicExpresso.Core/Resources/ErrorMessages.Designer.cs
src/DynamicExpresso.Core/Resources/ErrorMessages.resx
test/DynamicExpresso.UnitTest/GithubIssues.cs
test/DynamicExpresso.UnitTest/InvalidExpressionTest.cs
test/DynamicExpresso.UnitTest/MemberInvocationTest.cs
test/DynamicExpresso.UnitTest/OperatorsTest.cs

- Support array element assignment 
- Support indexing of multi-dimensional arrays
- Support indexer assignment 
Partially resolve #39

Improved indexing

---

src/DynamicExpresso.Core/Parsing/Parser.cs
test/DynamicExpresso.UnitTest/MemberInvocationTest.cs

When an argument default value is gathered from a method definition be sure to pass also its associated argument when creating the Expression.Constant.
This avoids a problem which happens when the argument is null: in this case the type of the argument will be System.Object and that will fail when binding the arguments to a method defining a different type (for example string)
Additionally see remarks section from https://docs.microsoft.com/en-us/dotnet/api/system.linq.expressions.expression.constant?view=netframework-4.7.2#System_Linq_Expressions_Expression_Constant_System_Object_ )
In addition a new unit test was added to showcase this situation.

Handle default parameters type explicitly

---

src/DynamicExpresso.Core/Parsing/Parser.cs
test/DynamicExpresso.UnitTest/NullableTest.cs

The C# compiler automatically allows for a comparison of types and their nullables, because even though the specific operators (\<, \>, ==, !=, ...) might not be explicitly defined between T and Nullable\<T\>, they are automatically generated.
However, this does not happen for expressions. 
This PR emulates what is automatically generated by explicitly converting the T to Nullable\<T\> to then allow for a comparisons between Nullable\<T\> and Nullable\<T\>. 
Closes #123

Fix problems in the comparison of types and their nullable counterparts. 

---

src/DynamicExpresso.Core/DynamicExpresso.Core.csproj
src/DynamicExpresso.Core/Parsing/Parser.cs
test/DynamicExpresso.UnitTest/DynamicTest.cs

Add Microsoft.CSharp package to allow for dynamic types in .Net Standard 2.0

Allow dynamic types for .NET Standard build #111

---

src/DynamicExpresso.Core/Parsing/Parser.cs
src/DynamicExpresso.Core/Resources/ErrorMessages.Designer.cs
src/DynamicExpresso.Core/Resources/ErrorMessages.resx
test/DynamicExpresso.UnitTest/OperatorsTest.cs

This is an attempt at fixing #135 . The gist is to try to find the proper user defined operator instead of solely relying on the Linq resolution (which doesn't check the base classes).
There were already some tests for user defined operators, I've added a use case to expand on it.

Unary and binary operators: find the proper overload by also checking the base classes

---

src/DynamicExpresso.Core/Parsing/Parser.cs
test/DynamicExpresso.UnitTest/OperatorsTest.cs

This is a follow up of my previous PR #135 . If a user defined operator was only defined on the right operand's type, it was not taken into account..

Fix user defined operator resolution

---

src/DynamicExpresso.Core/Identifier.cs
src/DynamicExpresso.Core/Interpreter.cs
src/DynamicExpresso.Core/Parsing/Parser.cs
src/DynamicExpresso.Core/Resources/ErrorMessages.Designer.cs
src/DynamicExpresso.Core/Resources/ErrorMessages.resx
test/DynamicExpresso.UnitTest/VariablesTest.cs

This is an attempt to fix #82, without changing the public interface. 
The idea is to use a custom identifier for functions, that rely on a dummy, custom, Linq Expression that represents the list of possible delegates. During the method invocation resolution, we detect this custom Expression, and check each possible overload to see if it matches the argument list.
The unit test is:
```
[Test]
public void Keywords_with_overloaded_delegates()
{
Func<decimal, decimal> roundFunction1 = (userNumber) => Math.Round(userNumber);
Func<decimal, int, decimal> roundFunction2 = (userNumber, decimals) => Math.Round(userNumber, decimals);
var interpreter = new Interpreter();
interpreter.SetFunction("ROUND", roundFunction1);
interpreter.SetFunction("ROUND", roundFunction2);
Assert.AreEqual(3.13M, …
```

Allow the registration of function overloads

---

README.md
src/DynamicExpresso.Core/Parsing/Parser.cs
test/DynamicExpresso.UnitTest/DynamicTest.cs

Added support of accessing index of dynamic object

---

src/DynamicExpresso.Core/Parsing/Parser.cs
test/DynamicExpresso.UnitTest/DynamicExpresso.UnitTest.csproj
test/DynamicExpresso.UnitTest/GithubIssues.cs
test/DynamicExpresso.UnitTest/VariablesTest.cs

This fixes #144 by taking a delegate's invoke methods into account while resolving the method invocation of a function defined via `SetFunction`.

Fix #144: consider a delegate's invoke methods

---

src/DynamicExpresso.Core/Parsing/Parser.cs
test/DynamicExpresso.UnitTest/GithubIssues.cs

Fix #148.
#138 introduced a regression when chaining method calls after the invocation of a custom function registered via `SetFunction` (e.g. `MyFunc().First()`): the parsing of the expression was stopped after the method call.

No longer stop parsing an expression after invoking a custom function

---

src/DynamicExpresso.Core/Interpreter.cs
src/DynamicExpresso.Core/InterpreterOptions.cs
src/DynamicExpresso.Core/Parsing/Parser.cs
src/DynamicExpresso.Core/Parsing/ParserSettings.cs
test/DynamicExpresso.UnitTest/DynamicTest.cs

This is a follow up to my last pull request. 
Dynamic properties and methods of strongly type classes are currently not being recognized as such because the resulting expression if of type Object instead of a dynamic expression. 
The proposed change is to treat expressions on boxed objects as dynamic, allowing late binding.
I've included a test case of a particular use case of mine that was failing otherwise.

Bind dynamic properties and methods of strongly typed classes

---

src/DynamicExpresso.Core/Identifier.cs
test/DynamicExpresso.UnitTest/VariablesTest.cs

Fix one of the issue highlighted by #157

Prevent multiple registration of the same delegate with the same name

---

src/DynamicExpresso.Core/Parsing/Parser.cs
src/DynamicExpresso.Core/Resources/ErrorMessages.resx
test/DynamicExpresso.UnitTest/ConstructorTest.cs
test/DynamicExpresso.UnitTest/OperatorsTest.cs

The arity of the generic type is now considered when trying to get the reference type (e.g. `Tuple<,,>` is now looked up as ``Tuple`3`` during parsing).
That means it's possible to write:
```c#
target.Reference(typeof(Tuple<>));
target.Reference(typeof(Tuple<,>));
target.Reference(typeof(Tuple<,,>));
Assert.AreEqual(1, target.Eval("new Tuple<int>(1).Item1"));
Assert.AreEqual("My str item", target.Eval("new Tuple<int, string>(5, \"My str item\").Item2"));
Assert.AreEqual(3, target.Eval("new Tuple<int, int, int>(1, 2, 3).Item3"));
```
The old way is still working, but in that case you need to add the arity yourself:
```c#
target.Reference(typeof(Tuple<>), "Toto`1");
target.Reference(typeof(Tuple<,>), "Toto`2"); …
```

Improve generic type parsing and referencing

---

src/DynamicExpresso.Core/Parsing/Parser.cs
src/DynamicExpresso.Core/Resources/ErrorMessages.Designer.cs
src/DynamicExpresso.Core/Resources/ErrorMessages.resx
test/DynamicExpresso.UnitTest/MemberInvocationTest.cs

This is a fix for part of #191. The goal is to allow a `params` method parameter to be a generic. 
Use case:
```c#
private static class Utils
{
public static List<T> Array<T>(params T[] array)
{
return new List<T>(array);
}
}
target.Reference(typeof(Utils));
var listInt = target.Eval<List<int>>("Utils.Array(1, 2, 3)");
Assert.AreEqual(new[] { 1, 2, 3 }, listInt);
```
Previously, the generic type was not promoted from the actual array type.

Allow a params parameter to have a generic type

---

src/DynamicExpresso.Core/Parsing/Parser.cs
test/DynamicExpresso.UnitTest/GithubIssues.cs
test/DynamicExpresso.UnitTest/MemberInvocationTest.cs

This is mainly a fix for #191, but I also took the opportunity to improve the support of params arrays, to more closely match the C# specification.
For example, the following method calls are now properly resolved:
```c#
public static class Utils
{
public static int WithParamsArray(params int[] i) => 3;
public static int WithParamsArray(int i, params int[] j) => 4;
public static int WithParamsArray(int i, int j) => 5;
}
target.Reference(typeof(Utils));
var arr = new int[] { 2 };
target.SetVariable("arr", arr);
Assert.AreEqual(3, target.Eval("Utils.WithParamsArray(arr)"));
Assert.AreEqual(4, target.Eval("Utils.WithParamsArray(1)")); // improper call to int WithParamsArray(params int[] i)
Assert.AreEqual(4, target.Eval("Utils.WithParamsArray(1, arr)")); …
```

Improve MethodHasPriority algorithm

---

test/DynamicExpresso.UnitTest/LambdaExpressionTest.cs

Just added 2 unit tests for lambda expressions. They could be useful to avoid some regression in the future.

Add unit tests for lambda parse exception and and to check return type

---

src/DynamicExpresso.Core/Parsing/Parser.cs
test/DynamicExpresso.UnitTest/GithubIssues.cs

No longer crash when a lambda parameter argument type can't be parsed

---

src/DynamicExpresso.Core/Parsing/Parser.cs
src/DynamicExpresso.Core/Resources/ErrorMessages.Designer.cs
src/DynamicExpresso.Core/Resources/ErrorMessages.resx
test/DynamicExpresso.UnitTest/ConstructorTest.cs

This simply re-uses the existing method resolution, but for constructors (instead of a special resolution).
Fix #196

Added support of param arrays within constructors

---

src/DynamicExpresso.Core/Parsing/Parser.cs
src/DynamicExpresso.Core/Parsing/ParserSettings.cs
test/DynamicExpresso.UnitTest/LambdaExpressionTest.cs

Fix #200
It works by making all the initial expression parameters as variables of the lambda expression interpreter.

Allow a lambda expression to access the initial expression's parameters

---

src/DynamicExpresso.Core/Parsing/Parser.cs
test/DynamicExpresso.UnitTest/GithubIssues.cs
test/DynamicExpresso.UnitTest/NullableTest.cs

Promote all operands of binary operators.
When applying the ?. operator to nullable types, emit the member access on the underlying type.
Fix #205

Improve support of nullable types

---

src/DynamicExpresso.Core/Parsing/Parser.cs
test/DynamicExpresso.UnitTest/GithubIssues.cs

MethodHasPriority: use promoted parameters when the method's argument type is an inferred generic type.
Fixes #203

MethodHasPriority: improve resolution

---

src/DynamicExpresso.Core/Parsing/ParseSignatures.cs
src/DynamicExpresso.Core/Parsing/Parser.cs
src/DynamicExpresso.Core/Parsing/TokenId.cs
test/DynamicExpresso.UnitTest/OperatorsTest.cs

Add support of the unary bitwise complement operator (~)
Add support of the shift operators (>> and <<)
Fix #206
```c#
var x = 0b_1100_1001_0000_0000_0000_0000_0001_0001;
target.SetVariable("x", x);
Assert.Equal(~x, target.Eval<uint>("~x"));
Assert.Equal(x >> 4, target.Eval<uint>("x >> 4"));
Assert.Equal(x << 4, target.Eval<uint>("x << 4"));
```

Improve bitwise operations support

---

src/DynamicExpresso.Core/Parsing/Parser.cs
test/DynamicExpresso.UnitTest/MemberInvocationTest.cs

Fix incorrect overload resolution when two overloads differ only by params array arguments.
Fixes #214

Fix incorrect overload resolution

---

src/DynamicExpresso.Core/Parsing/Parser.cs
test/DynamicExpresso.UnitTest/GithubIssues.cs

No longer try to emit a constant expression for generic types with generic parameters

---

src/DynamicExpresso.Core/ParserArguments.cs
src/DynamicExpresso.Core/Parsing/ParserSettings.cs
test/DynamicExpresso.UnitTest/GithubIssues.cs

The comparers for the known types and identifiers were lost when cloning the parser settings.
I also took the opportunity to address the fact that case insensitivity wasn't used when resolving extension methods, which wasn't consistent. Now, extension methods are resolved with the proper case comparison.
Fixes #221

Case insensitivity option is now properly used inside lambda expressions

---

src/DynamicExpresso.Core/Detector.cs
test/DynamicExpresso.UnitTest/DetectIdentifiersTest.cs

I've added a regex to detect lambda parameters.
Fixes #226

The identifier detection now supports lambda parameters

---

src/DynamicExpresso.Core/Identifier.cs
src/DynamicExpresso.Core/Interpreter.cs
src/DynamicExpresso.Core/Parsing/Parser.cs
test/DynamicExpresso.UnitTest/GithubIssues.cs
test/DynamicExpresso.UnitTest/VariablesTest.cs

This PR is the continuation of #229. 
- Fix #159 by ensuring the all applicable methods are returned when no overload is the best
- Add Unset methods to remove existing identifiers from the interpreter 
- SetFunction no longer allows multiple delegates with the same signature to be registered: only the last one is kept

Fix registration of same method signature via SetFunction

---

README.md
src/DynamicExpresso.Core/LanguageConstants.cs
src/DynamicExpresso.Core/Parsing/Parser.cs
test/DynamicExpresso.UnitTest/IdentifiersTest.cs

Allows to implicitly access `this` identifier set either as a Variable or passed as a Parameter to have more concise expression.
In other word an emulation of `this` implicit argument passed to a method call.
```c#
const string Name = "John";
var context = new KeyValuePair<string, string>(nameof(Name), Name);
var interpreter = new Interpreter().SetVariable("this", context);
Assert.AreEqual(Name, interpreter.Eval("this.Value"));
Assert.AreEqual(Name, interpreter.Eval("Value"));
```
or
```c#
const string Name = "John";
var context = new KeyValuePair<string, string>(nameof(Name), Name);
var parameter = new Parameter("this", context.GetType());
var interpreter = new Interpreter();
Assert.AreEqual(Name, interpreter.Parse("this.Value", parameter).Invoke(context));
Assert.AreEqual(Name, …
```

implicit `this` reference #232.

---

src/DynamicExpresso.Core/Parsing/Parser.cs
test/DynamicExpresso.UnitTest/LiteralsTest.cs

The lexer took one more character than needed when parsing an hexadecimal or a binary literal:
```c#
4+0x124+5
```` 
Instead of `0x124`, the lexer considered `0x124+` to be the literal. Now, we backtrack one character to avoid this issue.
Fix #241

Fix issue when parsing hexadecimal and binary literals

---

src/DynamicExpresso.Core/Parsing/Parser.cs
src/DynamicExpresso.Core/Resources/ErrorMessages.Designer.cs
src/DynamicExpresso.Core/Resources/ErrorMessages.resx
test/DynamicExpresso.UnitTest/ConstructorTest.cs

First step towards fixing #194 : single-dimension array initialization.
You can now write:
```c#
var arr = target.Eval<int[]>("new int[] { 1, 2 }");
Assert.AreEqual(2, arr.Length);
Assert.AreEqual(1, arr[0]);
Assert.AreEqual(2, arr[1]);
```
Jagged arrays are also supported:
```c#
var arr = target.Eval<int[][]>("new int[][] { new int[] { 1, 2, }, new int[] { 3, 4, }, }");
```
Multidimensional arrays are not supported, because I couldn't find the Linq expression needed to create them: `NewArrayInit` can initialize a single dimension array with values, while `NewArrayBounds` can initialize a multidimension array, but without values. Considering how rare multidimensional arrays are, I think the limitation is not really an issue.

Add support of Single-Dimensional Arrays initialization

---

src/DynamicExpresso.Core/Parsing/Parser.cs
test/DynamicExpresso.UnitTest/GithubIssues.cs
test/DynamicExpresso.UnitTest/LambdaExpressionTest.cs

Issue #212 was really the issue here.  
When replicating the code given in Issue #256 the last "x.Grade" was being immediately resolved as the value from the parameter was being inserted directly.  In the previous implementation of "InterpreterExpression", it was creating it as a new ParameterExpression.  
This code update captures the "parent" ParameterExpressions as identifiers.
This is essentially what happens with compiled code, so instead of us having to create a class, Expression actually allows us to reference the existing Expression as an Identifier.
Fix #212, #200, #256

Issues 212, 256: Adding support for internal lambdas to reference parameters from the parent lambda

---

src/DynamicExpresso.Core/Lambda.cs
src/DynamicExpresso.Core/Parsing/Parser.cs
src/DynamicExpresso.Core/Resources/ErrorMessages.Designer.cs
src/DynamicExpresso.Core/Resources/ErrorMessages.resx
test/DynamicExpresso.UnitTest/ConstructorTest.cs
test/DynamicExpresso.UnitTest/ParametersTest.cs

Implementation of collection initializer syntax support for constructor #194   Managed to somehow close the original PR on accident during rebase operation [pull 246](https://github.com/dynamicexpresso/DynamicExpresso/pull/246), but all comments have now been resolved.
You can now write
```
target.Reference(typeof(System.Collections.Generic.List<>));
var intList = target.Eval<System.Collections.Generic.List<int>>("new List<int>(){1, 2, 3, 4, 5}");
Assert.AreEqual(5, intList.Count);
for (int i = 0; i < intList.Count; ++i)
{
Assert.AreEqual(i + 1, intList[i]);
}
or 
target.Eval<System.Collections.Generic.List<string>>("new List<string>(){string.Empty}");
```
as well as implementations supporting multiple parameters in the Add method such as 
`new …

Added support of collection initializer syntax.

---

src/DynamicExpresso.Core/Interpreter.cs
src/DynamicExpresso.Core/Parsing/Parser.cs
test/DynamicExpresso.UnitTest/DynamicTest.cs

Issue #93 
The major change made with this is that rather than performing the binding, somewhat greedily, on typeof(object), we leverage the actual instance present in the CallSiteBinder args parameter to get the actual type as late as possible.

Adding fuller support for resolving anonymous type data on a dynamic object

---

src/DynamicExpresso.Core/Parsing/Parser.cs
test/DynamicExpresso.UnitTest/GithubIssues.cs
test/DynamicExpresso.UnitTest/LambdaExpressionTest.cs

Consider curly brackets to decide when the body of a lambda stops

---

src/DynamicExpresso.Core/Parsing/Parser.cs
test/DynamicExpresso.UnitTest/GithubIssues.cs

When a method parameter is a fully closed generic type (ie doesn't depend on a method generic's parameters), we never converted the parsed lambda expression to an actual expression. 
Example:
```c#
[Test]
public void Lambda_Issue_262()
{
var list = new List<int> { 10, 30, 4 };
var options = InterpreterOptions.Default | InterpreterOptions.LambdaExpressions;
var interpreter = new Interpreter(options);
interpreter.SetVariable("b", new Functions());
interpreter.SetVariable("list", list);
var results = interpreter.Eval<List<int>>(@"b.Add(list, t => t + 10)");
Assert.AreEqual(new List<int> { 20, 40, 14 }, results);
}
public class Functions
{
public List<int> Add(List<int> list, Func<int, int> transform)
{
return list.Select(i => transform(i)).ToList();
}
}
```
In that case, `Func<int, int>` is …

Promotion InterpreterExpressions to lambda expressions

---

src/DynamicExpresso.Core/Parsing/Parser.cs
test/DynamicExpresso.UnitTest/GithubIssues.cs

When trying to parse a params array, promoting the first argument only makes sense if it might be the full array.
Fixes #263

Params array: only promote first argument if it can be an array

---

.github/workflows/ci.yml
src/DynamicExpresso.Core/Parsing/Parser.cs
test/DynamicExpresso.UnitTest/DynamicExpresso.UnitTest.csproj
test/DynamicExpresso.UnitTest/MemberInvocationTest.cs

Let's say you have a generic method with a generic constraint:
```c#
public T GenericMethodWithConstraint<T>(T input) where T : class
{
return input;
}
```
It's invalid to call this method with an `int`, because it violates the generic constraints.
This PR catches any generic constraint violation, to avoid crashing.
Fixes #270

No longer crash when trying to match a generic method that'll violate the generic constraints

---

src/DynamicExpresso.Core/Parsing/Parser.cs
test/DynamicExpresso.UnitTest/GithubIssues.cs

No longer promote generic types if their arguments aren't compatible

---

src/DynamicExpresso.Core/Parsing/Parser.cs
test/DynamicExpresso.UnitTest/GithubIssues.cs

After the changes introduced in #178, the parser no longer needs to move to the token after the known type.
Fixes #287

No longer move to the next token when parsing an `is` or `as` expression

---

src/DynamicExpresso.Core/Detector.cs
test/DynamicExpresso.UnitTest/DetectIdentifiersTest.cs

It also support identifiers that start with @.
This should follow more closely with the [C# specs  section 6.4.3](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/lexical-structure#643-identifiers).
Note that I removed the `\b` in the Regex in favor of checking for member access in the code, because the `@` is not part of `\w` and therefore that didn't work.
Fixes #269

Improve the identifier detection regex to support non-ascii identifiers

---

src/DynamicExpresso.Core/Parsing/Parser.cs
test/DynamicExpresso.UnitTest/GithubIssues.cs

This fixes issue #295 and does not fail any other tests, so I think this is probably the correct solution. 
Whether this should be extended/limited in some way based on InterpreterOptions.LateBindObject, I'm not sure.

Fix Issue #295

---

src/DynamicExpresso.Core/Parsing/Parser.cs
test/DynamicExpresso.UnitTest/GithubIssues.cs

As described in #305 , the bug is related to overridden indexer in inherited class. So, to fix it, I added an additional comparison to select indexer with higher priority - indexer that is declared in the descendant class.
Fix #305

Fix Issue #305

---

.github/workflows/ci.yml
.github/workflows/publish.yml
test/DynamicExpresso.UnitTest/DynamicExpresso.UnitTest.csproj
test/DynamicExpresso.UnitTest/GithubIssues.cs
test/DynamicExpresso.UnitTest/MemberInvocationTest.cs

Configured .NET runtime 8.0, removed support for .NET 3.1.
Close #311:  Add a test to demostrate that it is not a bug. `Substring` method in .NET (https://learn.microsoft.com/en-us/dotnet/api/system.string.substring?view=net-8.0#system-string-substring(system-int32-system-int32)) it is not defined for Decimal type, so if we force all types to be decimal it will not work unless you perform a cast to int.
```
var interpreter2 = new Interpreter().SetDefaultNumberType(DefaultNumberType.Decimal);
interpreter2.SetVariable("a", a);
// expected to throw because Substring is not defined for decimal
Assert.Throws<NoApplicableMethodException>(() => interpreter2.Eval("a.Substring(0, 2)"));
// It works if we cast to int
Assert.AreEqual("AA", interpreter2.Eval("a.Substring((int)0, (int)2)"));
```

feat: .net 8 and github issue 311

---

src/DynamicExpresso.Core/Detector.cs
test/DynamicExpresso.UnitTest/DetectIdentifiersTest.cs

No longer consider number literal suffixes as identifiers.

---

src/DynamicExpresso.Core/Exceptions/ParseException.cs
src/DynamicExpresso.Core/Parameter.cs
src/DynamicExpresso.Core/Parsing/InterpreterExpression.cs
src/DynamicExpresso.Core/Parsing/Parser.cs
src/DynamicExpresso.Core/Reflection/IndexerData.cs
src/DynamicExpresso.Core/Reflection/MemberFinder.cs
src/DynamicExpresso.Core/Reflection/MethodData.cs
src/DynamicExpresso.Core/Reflection/ReflectionExtensions.cs
src/DynamicExpresso.Core/Reflection/TypeUtils.cs
src/DynamicExpresso.Core/Resolution/ExpressionUtils.cs
src/DynamicExpresso.Core/Resolution/LateBinders.cs
src/DynamicExpresso.Core/Resolution/MethodResolution.cs

The `Parser.cs` class is huge, which prevents code reuse: for example, we could imagine reuse the resolution logic in the late binders for dynamic objects.
In any case, having smaller files should make the code easier to understand. Let me know what you think :)
The PR has been split into several smaller commits to make it easier to review (and to validate each step).

🚚 Split Parser.cs

---

src/DynamicExpresso.Core/DefaultNumberType.cs
src/DynamicExpresso.Core/Exceptions/AssignmentOperatorDisabledException.cs
src/DynamicExpresso.Core/Exceptions/DuplicateParameterException.cs
src/DynamicExpresso.Core/Exceptions/DynamicExpressoException.cs
src/DynamicExpresso.Core/Exceptions/NoApplicableMethodException.cs
src/DynamicExpresso.Core/Exceptions/ParseException.cs
src/DynamicExpresso.Core/Exceptions/ReflectionNotAllowedException.cs
src/DynamicExpresso.Core/Exceptions/UnknownIdentifierException.cs
src/DynamicExpresso.Core/Interpreter.cs
test/DynamicExpresso.UnitTest/LambdaExpressionTest.cs

Since we only compile for netstandard2.0, the compiler directive is no longer needed.

Remove unneeded NETSTANDARD1_6 compiler directives and unneeded usings

---

src/DynamicExpresso.Core/ParserArguments.cs
src/DynamicExpresso.Core/Parsing/Parser.cs
test/DynamicExpresso.UnitTest/GithubIssues.cs

With the current algorithm that parses known types, we first try to parse the type argument list before checking if there's a matching generic type definition in the known types. This leads to an improper error message when trying to perform a less than comparison on a unknown identifier, because we try to parse the comparison as the type argument list 😅 
```c#
var i = new Interpreter();
var x= i.Eval("b < 1"); // ParseException: '>' expected (at index 4). [misleading]
```
Fix #314

No longer try to parse a generic type if there's no possible candidates

---

src/DynamicExpresso.Core/Resources/ErrorMessages.de.resx

This PR adds German translations
It seems like it's not possible to create translations for an external assembly using ResourceManager, and we need the errors in German.
I noticed this localization was added in #36, if @davideicardi or @jasonhumberstone know how I could provide translations from my project I would also be open to that.
If you ever need updates for the translations feel free to ping me.
I based the translations based on my understanding (mother tongue) and Microsoft's documentation translation.

Add german translations

---

src/DynamicExpresso.Core/Detector.cs
src/DynamicExpresso.Core/DetectorOptions.cs
src/DynamicExpresso.Core/Interpreter.cs
test/DynamicExpresso.UnitTest/DetectIdentifiersTest.cs

Add logic to enable detection of complete variable name (ex. contact.firstname)

DetectIdentifier obtain complete variable name

---

src/DynamicExpresso.Core/Detector.cs

This improves the regex evaluation back to when we still had `\b` in front, while (hopefully) doing as it should.
For the test referenced in #331, this change drops us back to 90ms, which is still twice as slow as originally, but there's also more features supported now, so I find this acceptable.
@metoule Please check that this is doing what you meant. If I understood your comment about `\b` right, you had to remove it because that also matched `@`, so even though `@?` is included in the identifier part it was never captured. If so, then this lookbehind should model the same as `\b` but it respects `@` in front. Demo: https://regex101.com/r/WhA5GM/2
Close #291

feat(detectIdentifiers): re-introduce boundary check

---

src/DynamicExpresso.Core/Parsing/Parser.cs
test/DynamicExpresso.UnitTest/GithubIssues.cs

According [to the specs](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#1297-cast-expressions), a cast expression is:
```
cast_expression
: '(' type ')' unary_expression
;
```
In the current implementation, the grammar is 
```
cast_expression
: '(' type ')' expression
;
```
which is incorrect.
Fixes #341

Fix cast expression grammar

---

.github/workflows/ci.yml
.github/workflows/publish.yml
test/DynamicExpresso.UnitTest/DynamicExpresso.UnitTest.csproj

.NET5, .NET6 and .NET7 are out of support, so we can remove them from the list of TargetFrameworks of the Unit Test project.
This PR updates the Github actions accordingly.

Update test targets

---

src/DynamicExpresso.Core/Identifier.cs
src/DynamicExpresso.Core/Parsing/Parser.cs
src/DynamicExpresso.Core/Resolution/LateBinders.cs
test/DynamicExpresso.UnitTest/DynamicTest.cs
test/DynamicExpresso.UnitTest/GithubIssues.cs

This PR fixes two things:
* Normal method invocations with dynamic arguments, through the C# member binder
* Invocations of methods registered via `SetFunction` (the issue reported in #295), through the C# invoke binder. This is currently less powerful, because it doesn't support multiple overloads
Extension methods invocations are not touched; I didn't check the behavior of the C# compiler in that case.
Fixes #295

Add support of method invocation with dynamic arguments

---

src/DynamicExpresso.Core/Parsing/Parser.cs
src/DynamicExpresso.Core/Resolution/LateBinders.cs
test/DynamicExpresso.UnitTest/DynamicTest.cs

This allows to write:
```c#
dynamic dyn = new ExpandoObject();
dyn.Foo = new int[5];
var interpreter = new Interpreter().SetVariable("dyn", (object)dyn);
interpreter.Eval("dyn.Foo[2] = 5");
interpreter.Eval("dyn.Bar = \"foo\"");
Assert.That(dyn.Foo[2], Is.EqualTo(5));
Assert.That(dyn.Bar, Is.EqualTo("foo"));
```
The fix is bit tricky: when we parse the assignment, the left operand is a dynamic `GetMember` expression, which can't be assigned via an `Expression.Assign`. We must instead change the dynamic expression from a `GetMember` to a `SetMember`. Those bindings  are performed via our Late binders.
We fix the issue by adding a new interface `IConvertibleToWritableBinder` that can convert the read binder to a write binder.
Fixes #340

Add support of dynamic property and index assignments

---

src/DynamicExpresso.Core/Detector.cs
src/DynamicExpresso.Core/DetectorOptions.cs
test/DynamicExpresso.UnitTest/DetectIdentifiersTest.cs

Rollback #323 due to #351.
Fix #351.

rollback: mark DetectorOptions.IncludeChildren as obsolete and del implementation

---

src/DynamicExpresso.Core/Parsing/Parser.cs
test/DynamicExpresso.UnitTest/GithubIssues.cs

The expression we generate for the null-coalescing operator doesn't work for nullable types, because there's no comparison operator between a nullable type and an object:
```c#
const object nullConst = null;
int? MyVar = null;
return MyVar == nullConst ? 0 : MyVar; // <-- doesn't compile
```
This PR changes the generated expression for nullable types from `expr == null ? exprRight : expr` to `expr.HasValue ? expr.Value : exprRight`
Fix #368

Fix #368: generate proper expression for null-coalescing operators on nullable types
