- .gitignore
- appveyor.yml
Configuration file to run and display tests results on Appveyor CI
1. You will have to create an account on Appveyor (https://ci.appveyor.com).
2. Create a new project targetting DynamicExpresso
3. Launch a build or push to GitHub.
Every time you will push to GitHub, Tests will be run on Appveyor.
You can also configure GitHub to validate Pull Requests via AppVeyor.
> ADD: Appveyor configuration file

- DynamicExpresso.sln
- src/DynamicExpresso.Shared/Exceptions/AssignmentOperatorDisabledException.cs
- src/DynamicExpresso.Shared/Exceptions/DuplicateParameterException.cs
- src/DynamicExpresso.Shared/Exceptions/DynamicExpressoException.cs
- src/DynamicExpresso.Shared/Exceptions/ExceptionExtensions.cs
- src/DynamicExpresso.Shared/Exceptions/NoApplicableMethodException.cs
- src/DynamicExpresso.Shared/Exceptions/ParseException.cs
- src/DynamicExpresso.Shared/Exceptions/ReflectionNotAllowedException.cs
- src/DynamicExpresso.Shared/Exceptions/UnknownIdentifierException.cs
- src/DynamicExpresso.Shared/Lambda.cs
- src/DynamicExpresso.Shared/Parsing/Parser.cs
- src/DynamicExpresso.Shared/Parsing/ParserSettings.cs
- src/DynamicExpresso.Shared/Reflection/ReflectionExtensions.cs
- src/DynamicExpresso.Universal/DynamicExpresso.Universal.csproj
Hi Davide,
I'm trying to advance the state of the dotnetcore branch and have some commits for you to pull. 
I started working on the DynamicExpresso.Exception namespace, removed serialization and tried to find a workaround for the PreserveStackTrace issue under NetCore (using ExceptionDispatchInfo). 
Next I'll fix all issues in the remaining classes.
I've already worked my way through all classes in an offline copy of the repo - including the test project - and got most of the tests to run successfully. 
Please check out my changes. There are some issues to discuss now (Target Framework Moniker, PreserveStackTrace) and much more later (NetCore Reflection, ExpressionCreator).
> Building the UAP version of DynamicExpresso

- src/DynamicExpresso.Core/Parsing/Parser.cs
- test/DynamicExpresso.UnitTest/DynamicTest.cs
> Fix Issue "Nested dynamic objects #54"

- src/DynamicExpresso.Core/Parsing/Parser.cs
- test/DynamicExpresso.UnitTest/GenerateDelegatesTest.cs
- test/DynamicExpresso.UnitTest/GenerateLambdaTest.cs
- test/DynamicExpresso.UnitTest/GithubIssues.cs
- test/DynamicExpresso.UnitTest/LiteralsTest.cs
Fix for #43 when .2 was not parsing is a Real Literal.
Added additional Unit Tests for the new parsing.
Not sure what went wrong is the spacings.
> Fix for #43 when .2 was not parsing is a Real Literal.

- src/DynamicExpresso.Core/Parsing/Parser.cs
- src/DynamicExpresso.Core/Parsing/TokenId.cs
- test/DynamicExpresso.UnitTest/OperatorsTest.cs
> add Exclusive Or operator

- .vscode/settings.json
- src/DynamicExpresso.Core/Exceptions/ParseException.cs
- src/DynamicExpresso.Core/Parsing/Parser.cs
- src/DynamicExpresso.Core/Resources/ErrorMessages.Designer.cs
- src/DynamicExpresso.Core/Resources/ErrorMessages.resx
- test/DynamicExpresso.UnitTest/GithubIssues.cs
- test/DynamicExpresso.UnitTest/OperatorsTest.cs
> Handle invalid operation with ParseException

- src/DynamicExpresso.Core/Parsing/Parser.cs
- test/DynamicExpresso.UnitTest/GithubIssues.cs
- test/DynamicExpresso.UnitTest/LiteralsTest.cs
> Dynamic Expresson fix parsing of Exponential format number

- src/DynamicExpresso.Core/Parsing/Parser.cs
- src/DynamicExpresso.Core/Parsing/TokenId.cs
- src/DynamicExpresso.Core/Resources/ErrorMessages.Designer.cs
- src/DynamicExpresso.Core/Resources/ErrorMessages.resx
- test/DynamicExpresso.UnitTest/ConstructorTest.cs
This PR adds support of object initializers, so that it's possible to write `new MyClass { MyProp = 5 }`.
> Added support of object initializers

- src/DynamicExpresso.Core/Parameter.cs
> Added new constructor in Parameter with ParameterExpression

- src/DynamicExpresso.Core/Parsing/Parser.cs
- test/DynamicExpresso.UnitTest/DynamicTest.cs
This commit adds the ability to do unary, binary and conditional operations on dynamic types 
should address https://github.com/davideicardi/DynamicExpresso/issues/72
> add dynamic unary, binary and conditional operations support

- src/DynamicExpresso.Core/Parsing/Parser.cs
- test/DynamicExpresso.UnitTest/OperatorsTest.cs
Fixes #151 
It would be great if you could review my changes for Parser.GenerateStringConcat method in this pull request.
PS. I also added two static fields for MethodInfos you use in there so that they won't have to be calculated on each call
> Refactored method GenerateStringConcat in Parser.cs

- README.md
> Fix misspelling in readme

- src/DynamicExpresso.Core/DynamicExpresso.Core.csproj
Updated csproj info to publish correct information to nuget.
> Update repository links in csproj for nuget

- README.md
- src/DynamicExpresso.Core/DynamicExpresso.Core.csproj
- test/DynamicExpresso.UnitTest/DynamicExpresso.UnitTest.csproj
> Change project target frameworks

- README.md
- src/DynamicExpresso.Core/DynamicExpresso.Core.csproj
- test/DynamicExpresso.UnitTest/DynamicExpresso.UnitTest.csproj
I forgot to cleanup certain parts of the csprojs.
> Cleanup csproj after removing support for .NET Framework

- src/DynamicExpresso.Core/Parsing/Parser.cs
- test/DynamicExpresso.UnitTest/LiteralsTest.cs
> Add support for hexadecimal and binary literals (0x and 0b)

- src/DynamicExpresso.Core/Parsing/Parser.cs
- test/DynamicExpresso.UnitTest/GithubIssues.cs
> Handle unary operator on enums

- .github/workflows/ci.yml
- .github/workflows/publish.yml
To fix https://github.com/dynamicexpresso/DynamicExpresso/actions/runs/4509481835
> feat: update github workflows

- .github/workflows/publish.yml
- src/GlobalAssemblyInfo.cs
Fix package namespace for github, to fix https://github.com/dynamicexpresso/DynamicExpresso/actions/runs/4511922121
:crossed_fingers:
> fix: nuget package directory

- .github/FUNDING.yml
https://github.com/sponsors/metoule :)
> Edit FUNDING.yml to add myself

- src/DynamicExpresso.Core/Detector.cs
- src/DynamicExpresso.Core/LanguageConstants.cs
- src/DynamicExpresso.Core/ParserArguments.cs
- src/DynamicExpresso.Core/Parsing/Parser.cs
- src/DynamicExpresso.Core/Reflection/ReflectionExtensions.cs
- src/DynamicExpresso.Core/Resolution/LateBinders.cs
* Use `var` everywhere (I can revert if not wanted)
* Remove unused method arguments
* Use pattern matching 
* Fix formatting issues
> Code format: fix compilation suggestions
